sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=isort
# command to install dependencies
install:
  - pip install -r requirements/requirements_dev.txt
# command to run tests
script:
  - tox -e "${TOX_ENV}"
