dist: xenial
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install tox-travis
# command to run tests
script:
  - tox
after_success:
- tox -e coverage-report
- codecov
